In [10]:
%pip install kagglehub

Requirement already satisfied: kagglehub in c:\users\user\anaconda3\lib\site-packages (1.0.0)
Requirement already satisfied: kagglesdk<1.0,>=0.1.14 in c:\users\user\anaconda3\lib\site-packages (from kagglehub) (0.1.19)
Requirement already satisfied: packaging in c:\users\user\anaconda3\lib\site-packages (from kagglehub) (24.2)
Requirement already satisfied: pyyaml in c:\users\user\anaconda3\lib\site-packages (from kagglehub) (6.0.3)
Requirement already satisfied: requests in c:\users\user\anaconda3\lib\site-packages (from kagglehub) (2.32.3)
Requirement already satisfied: tqdm in c:\users\user\anaconda3\lib\site-packages (from kagglehub) (4.67.1)
Requirement already satisfied: protobuf in c:\users\user\anaconda3\lib\site-packages (from kagglesdk<1.0,>=0.1.14->kagglehub) (5.29.3)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\user\anaconda3\lib\site-packages (from requests->kagglehub) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\user\anaconda3\lib\site-packages (from requests->kagglehub) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\user\anaconda3\lib\site-packages (from requests->kagglehub) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\user\anaconda3\lib\site-packages (from requests->kagglehub) (2026.1.4)
Requirement already satisfied: colorama in c:\users\user\anaconda3\lib\site-packages (from tqdm->kagglehub) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [11]:
import numpy as np
import pandas as pd
import kagglehub
from kagglehub import KaggleDatasetAdapter
import os
import urllib.request
import zipfile

In [12]:
class KaggleDatasetDownloader:
    def __init__(self, links, base_dir="Datasets"):
        self.links = links
        self.base_dir = os.path.abspath(base_dir)

    def download(self):
        os.makedirs(self.base_dir, exist_ok=True)

        for dataset in self.links:
            print(f"\nDownloading: {dataset}")
            path = kagglehub.dataset_download(dataset)

            dataset_name = dataset.split('/')[-1]
            save_dir = os.path.join(self.base_dir, dataset_name)
            os.makedirs(save_dir, exist_ok=True)

            print(f"Saving to: {save_dir}")

            for file in os.listdir(path):
                if file.endswith(".csv"):
                    print(f"  → {file}")
                    df = pd.read_csv(os.path.join(path, file), low_memory=False)
                    df.to_csv(os.path.join(save_dir, file), index=False)

        print("\nAll datasets saved successfully!")

    def add_dataset(self, dataset_link):
        self.links.append(dataset_link)

In [13]:
links = [
    "lakshmi25npathi/imdb-dataset-of-50k-movie-reviews",
    "rounakbanik/the-movies-dataset"
]

downloader = KaggleDatasetDownloader(links)

# Run whenever you want
#downloader.download()

# Add more datasets later
# downloader.add_dataset("new/dataset-link")
# downloader.download()

In [15]:
class MovieLensDownloader:
    def __init__(self):
        self.url = "https://files.grouplens.org/datasets/movielens/ml-25m.zip"
        self.base_save_dir = os.path.abspath("Datasets")
        self.dataset_name = "movielens-25m"

        self.save_dir = os.path.join(self.base_save_dir, self.dataset_name)
        self.zip_path = os.path.join(self.save_dir, "ml-25m.zip")

    def run(self):
        # Create folder
        os.makedirs(self.save_dir, exist_ok=True)

        # Download
        print("Please wait, this might take a moment...")
        urllib.request.urlretrieve(self.url, self.zip_path)
        print("Download complete!")

        # Extract
        print("Extracting CSV files...")
        with zipfile.ZipFile(self.zip_path, 'r') as zip_ref:
            for member in zip_ref.namelist():
                filename = os.path.basename(member)

                if filename:
                    print(f"Extracting: {filename}")

                    source = zip_ref.open(member)
                    target_path = os.path.join(self.save_dir, filename)

                    with open(target_path, "wb") as target:
                        target.write(source.read())

        print("Done!")

In [ ]:
ml_downloader = MovieLensDownloader()

# To download use run method
# ml_downloader.run()

Please wait, this might take a moment...
Download complete!
Extracting CSV files...
Extracting: tags.csv
Extracting: links.csv
Extracting: README.txt
Extracting: ratings.csv
Extracting: genome-tags.csv
Extracting: genome-scores.csv
Extracting: movies.csv
Done!

In [17]:
df = pd.read_csv(r"D:\CINEIQ\CINEIQ\Datasets\movielens-25m\tags.csv")

In [ ]:
class TagGenomeDownloader:
    def __init__(self):
        self.url = "https://files.grouplens.org/datasets/tag-genome-2021/genome_2021.zip"
        self.base_save_dir = os.path.abspath("Datasets")
        self.dataset_name = "tag-genome-2021"

        self.save_dir = os.path.join(self.base_save_dir, self.dataset_name)
        self.zip_path = os.path.join(self.save_dir, "genome_2021.zip")

    def run(self):
        # Create folder
        os.makedirs(self.save_dir, exist_ok=True)

        # Download
        print("Please wait, this might take a moment...")
        urllib.request.urlretrieve(self.url, self.zip_path)
        print("Download complete!")

        # Extract
        print("Extracting CSV files...")
        with zipfile.ZipFile(self.zip_path, 'r') as zip_ref:
            for member in zip_ref.namelist():
                filename = os.path.basename(member)

                if filename:
                    print(f"Extracting: {filename}")

                    source = zip_ref.open(member)
                    target_path = os.path.join(self.save_dir, filename)

                    with open(target_path, "wb") as target:
                        target.write(source.read())

        print("Done!")

In [ ]:
genome=TagGenomeDownloader()

# to download use run method
# genome.run()

In [19]:
folder_path=r"D:\CINEIQ\CINEIQ\Datasets\the-movies-dataset\{}.csv"
files=['credits','keywords','links','links_small','movies_metadata','ratings_small','ratings']
dataframes={}
for file in files:
    dataframes[file] = pd.read_csv(folder_path.format(file),low_memory=False)

In [20]:
folder_path=r"D:\CINEIQ\CINEIQ\Datasets\movielens-25m\{}.csv"
files=['movies','genome-tags','genome-scores']
dataframes2={}
for file in files:
    dataframes2[file] = pd.read_csv(folder_path.format(file),low_memory=False)

## IMDB 
1. IMDB dataset has response(positive/negetive) of movie with shape (50000, 2) no id 
2. this data is only to train llm/npl/transformer for the sentiment prediction 

## the-movies datset 
1. credit(45476, 3) and keywords(46419, 2) and movies_metadata(45466, 24) has a column id on which we can merge 
2. links_small (9125, 3) and links(45843, 3) has a tmdbId which is same as id of credit
3. links has shape (45843, 3) and links_small has shape (9125, 3)
4. ratings_small has a column movieid on which we can merge shape (100004, 4) 
5. rating has a column movieid shape (26024289, 4) can stack with ratings_small

## movielens -25m

1. links file has (62423,3) shape 
2. genome-scores has (15584448, 3) shape 
3. genome-tag has (1128, 2) shape 
4. movies has (62423, 3) shape 
5. rating has (25000095, 4) shape
6. tags has (1093360, 4) shape

In [21]:
credits_df=dataframes['credits']
keywords_df=dataframes['keywords']
links_df=dataframes['links']
links_small_df=dataframes['links_small']
movies_metadata_df=dataframes['movies_metadata']
ratings_df=dataframes['ratings']
ratings_small_df=dataframes['ratings_small']
movies_df=dataframes2['movies']
genome_tags_df=dataframes2['genome-tags']
genome_scores_df=dataframes2['genome-scores']

In [22]:
movies_df

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy
...,...,...,...
62418,209157,We (2018),Drama
62419,209159,Window of the Soul (2001),Documentary
62420,209163,Bad Poems (2018),Comedy|Drama
62421,209169,A Girl Thing (2001),(no genres listed)
62422,209171,Women of Devil's Island (1962),Action|Adventure|Drama

In [23]:
credits_df.head()

,cast,crew,id
0,"[{'cast_id': 14, 'character': 'Woody (voice)',...","[{'credit_id': '52fe4284c3a36847f8024f49', 'de...",862
1,"[{'cast_id': 1, 'character': 'Alan Parrish', '...","[{'credit_id': '52fe44bfc3a36847f80a7cd1', 'de...",8844
2,"[{'cast_id': 2, 'character': 'Max Goldman', 'c...","[{'credit_id': '52fe466a9251416c75077a89', 'de...",15602
3,"[{'cast_id': 1, 'character': ""Savannah 'Vannah...","[{'credit_id': '52fe44779251416c91011acb', 'de...",31357
4,"[{'cast_id': 1, 'character': 'George Banks', '...","[{'credit_id': '52fe44959251416c75039ed7', 'de...",11862

In [24]:
keywords_df.head()

      id                                           keywords
0    862  [{'id': 931, 'name': 'jealousy'}, {'id': 4290,...
1   8844  [{'id': 10090, 'name': 'board game'}, {'id': 1...
2  15602  [{'id': 1495, 'name': 'fishing'}, {'id': 12392...
3  31357  [{'id': 818, 'name': 'based on novel'}, {'id':...
4  11862  [{'id': 1009, 'name': 'baby'}, {'id': 1599, 'n...

In [25]:
links_small_df.shape

(9125, 3)

In [26]:
movies_metadata_df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0

In [27]:
combined_links = pd.concat([links_df, links_small_df], axis=0, ignore_index=True)

In [28]:
combined_links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [29]:
combined_links.shape

(54968, 3)

In [30]:
combined_ratings = pd.concat([ratings_df, ratings_small_df], axis=0, ignore_index=True)

In [31]:
combined_ratings.shape

(26124293, 4)

In [32]:
combined_ratings.head()

   userId  movieId  rating   timestamp
0       1      110     1.0  1425941529
1       1      147     4.5  1425942435
2       1      858     5.0  1425941523
3       1     1221     5.0  1425941546
4       1     1246     5.0  1425941556

In [33]:
combined_links.head()

   movieId  imdbId   tmdbId
0        1  114709    862.0
1        2  113497   8844.0
2        3  113228  15602.0
3        4  114885  31357.0
4        5  113041  11862.0

In [34]:
movies_metadata_df["id"] = pd.to_numeric(movies_metadata_df["id"], errors="coerce")

In [35]:
df = credits_df.merge(keywords_df,on="id", how="outer") \
        .merge(combined_links, left_on="id", right_on="tmdbId", how="outer") \
        .merge(movies_metadata_df,on="id", how="outer")

## **Basic Info About All Columns In Data**

1. `cast` has info about all actors.
2. `crew` has info about who have done all the production work.
3. Here `id`  and `tmdbId` has same id of a movie.
4. `keywords` contains tags that describe the themes or important ideas in the movie.
5. `imdbId` and `imdb_id` both are same but `imdb_id` is in right format(tt0094675) and it has some missing values so we can fill it from `imdbId`(only 1 missing values) and then we can drop `imdbId`.
6. `belongs_to_collection` column tells whether a movie is part of a series/franchise and gives the name of that collection(that's why the column has less value as all movie are not a part of series).But in some place it has some weird number that is the data is corrupted.
7. `budget` column contain info about total amount spent to produce that movie but this column also has some corrupted value.
8. `genres` has info that what type/category this movie belong to.
9. `homepage` has info about Official website URL of the movie and also in some row it contain the value which should be in `production_country` column(so we need to extract them).
10. `original_language` has info about in which language this movie is.but it contain some weired number which may be data of different column(need checking).
11. `original_title` has the title(real name of the movie in which language it is made) of the movie here in some row we have value of `spoken_language` column so the columns are mixed and also we have repeated name so need checking that are they same movie or different version of same movie.
12. `overview` has brief movie description but it is mixed up with status column as it has 'released' as value which should be in status column.
13. `popularity` column has scores that how popular this movie is but it is mixed up with may be 'tagline' column as in some place has value like 'Beware Of Frost Bites'.
14. `production_companies` has info company name it has also value like 'False' in many rows which need to be corrected.
15. `adult` should contain two values 'False'(normal movie) and 'True' (adult movie:for 18+years) but in some places it have text(may be from overview column) like 3 text each 424 times(need checking).
16. `production_countries` give info that which country produce that movie.
17. `release_date` has info when the movie is released it is also corrupted as (12,1,22 this 3 value contain each 424 times and this colulmn also has lot of missing values).
18. `revenue` give info that how much money the movie earned (it has a lot of 0 values(43676) and nan values also)(need cleaning).
19. `runtime` contain total movie time(in min).
20. `spoken_language` contain info that what all language used in this movie.
21. `status` give current statge of movies lifecycle(so from here we have to show only those movies which are released for recomendation).
22. `tagline` is basically a short promotional sentence for marketing.
23. `title` has title(standerdized title(baiscally in english)) of the movie but it has many repeated values(so need checking are they really same movie or not).so we may be merge this column with 'original_title' column after cleaning and use that column in tf_idf.
24. `video` has info about the movie trailor availabilty in this dataset(so only two values False and True)(not usefull for TfIdf may be used for filltering).
25. `vote_average` give average rating score of that movie.
26. `vote_count` give how many users rated that movie. here we can merge this two column for filltering the movie after TfIdf.
* **`cast`,`crew`,`keywords`,`belongs_to_collection`,`genres`,`production_companies`,
`production_countries`,`spoken_language` all are in string format first need to parse them to make a list of dictionary for extract info from it.**

In [36]:
#missing value percentage in each column
(df.isnull().mean() * 100).to_frame().T

,cast,crew,id,keywords,movieId,imdbId,tmdbId,adult,belongs_to_collection,budget,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,2.217693,2.217693,2.215951,2.217693,0.001742,0.001742,1.214243,0.0,86.826243,0.0,...,0.153305,2.222919,2.682833,2.222919,2.369255,51.236891,2.222919,2.222919,2.222919,2.222919

In [37]:
print(df['id'].duplicated().sum())
print(df.duplicated().sum())

11968
10718

In [38]:
df[['genres','movieId','title','tmdbId']].head(6)

,genres,movieId,title,tmdbId
0,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",4470.0,Ariel,2.0
1,"[{'id': 18, 'name': 'Drama'}, {'id': 80, 'name...",4470.0,Ariel,2.0
2,"[{'id': 18, 'name': 'Drama'}, {'id': 35, 'name...",61724.0,Shadows in Paradise,3.0
3,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",18.0,Four Rooms,5.0
4,"[{'id': 80, 'name': 'Crime'}, {'id': 35, 'name...",18.0,Four Rooms,5.0
5,"[{'id': 28, 'name': 'Action'}, {'id': 53, 'nam...",479.0,Judgment Night,6.0

In [39]:
movies_df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [40]:
pd.set_option('display.max_columns', None)

pd.set_option('display.max_colwidth', None)
df['vote_count'].value_counts()

vote_count
1.0       3449
2.0       3294
0.0       3097
3.0       3072
4.0       2647
          ...
1959.0       1
799.0        1
651.0        1
714.0        1
357.0        1
Name: count, Length: 1820, dtype: int64

In [41]:
df.columns

Index(['cast', 'crew', 'id', 'keywords', 'movieId', 'imdbId', 'tmdbId',
       'adult', 'belongs_to_collection', 'budget', 'genres', 'homepage',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [42]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57402 entries, 0 to 57401
Data columns (total 30 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   cast                   56129 non-null  object
 1   crew                   56129 non-null  object
 2   id                     56130 non-null  float64
 3   keywords               56129 non-null  object
 4   movieId                57401 non-null  float64
 5   imdbId                 57401 non-null  float64
 6   tmdbId                 56705 non-null  float64
 7   adult                  57402 non-null  object
 8   belongs_to_collection  7562 non-null   object
 9   budget                 57402 non-null  object
 10  genres                 57402 non-null  object
 11  homepage               11322 non-null  object
 12  imdb_id                57385 non-null  object
 13  original_language      57391 non-null  object
 14  original_title         57402 non-null  object
 15  overview               56395 non-null  object
 16  popularity             56550 non-null  object
 17  poster_path            57000 non-null  object
 18  production_companies   57398 non-null  object
 19  production_countries   57398 non-null  object
 20  release_date           57314 non-null  object
 21  revenue                56126 non-null  float64
 22  runtime                55862 non-null  float64
 23  spoken_languages       56126 non-null  object
 24  status                 56042 non-null  object
 25  tagline                27991 non-null  object
 26  title                  56126 non-null  object
 27  video                  56126 non-null  object
 28  vote_average           56126 non-null  float64
 29  vote_count             56126 non-null  float64
dtypes: float64(8), object(22)
memory usage: 13.1+ MB

In [44]:
df3=pd.read_csv(r'D:\CINEIQ\CINEIQ\Datasets\the-movies-dataset\movies_metadata.csv')
df3.genres.iloc[0]

C:\Users\USER\AppData\Local\Temp\ipykernel_32408\1236744398.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df3=pd.read_csv(r'D:\CINEIQ\CINEIQ\Datasets\the-movies-dataset\movies_metadata.csv')

"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]"

In [46]:
df3.head().transpose()

,0,1,2,3,4
adult,False,False,False,False,False
belongs_to_collection,"{'id': 10194, 'name': 'Toy Story Collection', 'poster_path': '/7G9915LfUQ2lVfwMEEhDsn3kT4B.jpg', 'backdrop_path': '/9FBwqcd9IRruEDUrTdcaafOMKUq.jpg'}",NaN,"{'id': 119050, 'name': 'Grumpy Old Men Collection', 'poster_path': '/nLvUdqgPgm3F85NMCii9gVFUcet.jpg', 'backdrop_path': '/hypTnLot2z8wpFS7qwsQHW1uV8u.jpg'}",NaN,"{'id': 96871, 'name': 'Father of the Bride Collection', 'poster_path': '/nts4iOmNnq7GNicycMJ9pSAn204.jpg', 'backdrop_path': '/7qwE57OVZmMJChBpLEbJEmzUydk.jpg'}"
budget,30000000,65000000,0,16000000,0
genres,"[{'id': 16, 'name': 'Animation'}, {'id': 35, 'name': 'Comedy'}, {'id': 10751, 'name': 'Family'}]","[{'id': 12, 'name': 'Adventure'}, {'id': 14, 'name': 'Fantasy'}, {'id': 10751, 'name': 'Family'}]","[{'id': 10749, 'name': 'Romance'}, {'id': 35, 'name': 'Comedy'}]","[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'name': 'Drama'}, {'id': 10749, 'name': 'Romance'}]","[{'id': 35, 'name': 'Comedy'}]"
homepage,http://toystory.disney.com/toy-story,NaN,NaN,NaN,NaN
id,862,8844,15602,31357,11862
imdb_id,tt0114709,tt0113497,tt0113228,tt0114885,tt0113041
original_language,en,en,en,en,en
original_title,Toy Story,Jumanji,Grumpier Old Men,Waiting to Exhale,Father of the Bride Part II
overview,"Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences.","When siblings Judy and Peter discover an enchanted board game that opens the door to a magical world, they unwittingly invite Alan -- an adult who's been trapped inside the game for 26 years -- into their living room. Alan's only hope for freedom is to finish the game, which proves risky as all three find themselves running from giant rhinoceroses, evil monkeys and other terrifying creatures.","A family wedding reignites the ancient feud between next-door neighbors and fishing buddies John and Max. Meanwhile, a sultry Italian divorcée opens a restaurant at the local bait shop, alarming the locals who worry she'll scare the fish away. But she's less interested in seafood than she is in cooking up a hot time with Max.","Cheated on, mistreated and stepped on, the women are holding their breath, waiting for the elusive ""good man"" to break a string of less-than-stellar lovers. Friends and confidants Vannah, Bernie, Glo and Robin talk it all out, determined to find a better way to breathe.","Just when George Banks has recovered from his daughter's wedding, he receives the news that she's pregnant ... and that George's wife, Nina, is expecting too. He was planning on selling their home, but that's a plan that -- like George -- will have to change with the arrival of both a grandchild and a kid of his own."
popularity,21.946943,17.015539,11.7129,3.859495,8.387519
poster_path,/rhIRbceoE9lR4veEXuwCC2wARtG.jpg,/vzmL6fP7aPKNKPRTFnZmiUfciyV.jpg,/6ksm1sjKMFLbO7UY2i6G1ju9SML.jpg,/16XOMpEaLWkrcPqSQqhTmeJuqQl.jpg,/e64sOI48hQXyru7naBFyssKFxVd.jpg
production_companies,"[{'name': 'Pixar Animation Studios', 'id': 3}]","[{'name': 'TriStar Pictures', 'id': 559}, {'name': 'Teitler Film', 'id': 2550}, {'name': 'Interscope Communications', 'id': 10201}]","[{'name': 'Warner Bros.', 'id': 6194}, {'name': 'Lancaster Gate', 'id': 19464}]","[{'name': 'Twentieth Century Fox Film Corporation', 'id': 306}]","[{'name': 'Sandollar Productions', 'id': 5842}, {'name': 'Touchstone Pictures', 'id': 9195}]"
production_countries,"[{'iso_3166_1': 'US', 'name': 'United States of America'}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]","[{'iso_3166_1': 'US', 'name': 'United States of America'}]"
release_date,1995-10-30,1995-12-15,1995-12-22,1995-12-22,1995-02-10
revenue,373554033.0,262797249.0,0.0,81452156.0,76578911.0
runtime,81.0,104.0,101.0,127.0,106.0
spoken_languages,"[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}, {'iso_639_1': 'fr', 'name': 'Français'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]","[{'iso_639_1': 'en', 'name': 'English'}]"
status,Released,Released,Released,Released,Released
tagline,NaN,Roll the dice and unleash the excitement!,Still Yelling. Still Fighting. Still Ready for Love.,Friends are the people who let you be yourself... and never let you forget it.,Just When His World Is Back To Normal... He's In For The Surprise Of His Life!
title,Toy Story,Jumanji,Grumpier Old Men,Waiting to Exhale,Father of the Bride Part II
video,False,False,False,False,False
vote_average,7.7,6.9,6.5,6.1,5.7
vote_count,5415.0,2413.0,92.0,34.0,173.0

In [50]:
combined_ratings.shape

(26124293, 4)

In [51]:
df1=df.copy()

In [52]:
pd.set_option('display.max_colwidth', None)
print(df1['cast'].sample(1))
print(df1['crew'].sample(1))
print(df1['keywords'].sample(1))
print(df1['spoken_languages'].sample(1))
print(df1['production_companies'].sample(1))
print(df1['genres'].sample(1))
print(df1['production_countries'].sample(1))

46774    [{'cast_id': 3, 'character': 'Anna', 'credit_id': '52fe4db5c3a368484e1f854f', 'gender': 1, 'id': 565225, 'name': 'Roseanne Supernault', 'order': 0, 'profile_path': '/6E5B23dGrbAIofERE6g5WM35hBy.jpg'}, {'cast_id': 4, 'character': 'Popper', 'credit_id': '52fe4db5c3a368484e1f8553', 'gender': 2, 'id': 131336, 'name': 'Mark Antony Krupa', 'order': 1, 'profile_path': '/1Dr01rhl2CMEbgY0zJSl54w6v2A.jpg'}, {'cast_id': 5, 'character': 'Aila', 'credit_id': '52fe4db5c3a368484e1f8557', 'gender': 0, 'id': 1197101, 'name': 'Devery Jacobs', 'order': 2, 'profile_path': '/6ZzD898Mxqg3B7Y53rDzA2vjLWz.jpg'}, {'cast_id': 6, 'character': 'Priest #1', 'credit_id': '52fe4db5c3a368484e1f855b', 'gender': 0, 'id': 115596, 'name': 'Arthur Holden', 'order': 3, 'profile_path': '/y0aCeMJKAzVJO3pydEiVCV2Ca4k.jpg'}, {'cast_id': 7, 'character': 'Joseph', 'credit_id': '55fbe41fc3a36826dd001e8b', 'gender': 0, 'id': 146174, 'name': 'Glen Gould', 'order': 4, 'profile_path': '/ey6yrx7i56ailDfWwDrAoTjZvkD.jpg'}, {'cast_id': 8, 'character': 'Burner', 'credit_id': '5662395dc3a3682bd80013be', 'gender': 0, 'id': 1529984, 'name': 'Brandon Oakes', 'order': 5, 'profile_path': '/mtxtI6CcFhYQmCcP3hPdK2r4g4P.jpg'}, {'cast_id': 9, 'character': 'Tammy', 'credit_id': '5662400d9251412ac40013c3', 'gender': 1, 'id': 1511946, 'name': 'Katie Nolan', 'order': 6, 'profile_path': '/2Om3sQUO1RYjThWw7nz85MG1rVS.jpg'}]
Name: cast, dtype: object
7133    [{'credit_id': '52fe437e9251416c750127eb', 'department': 'Directing', 'gender': 2, 'id': 1744, 'job': 'Director', 'name': 'Robert Wise', 'profile_path': '/6EPkRgYsDMQOYmE9s1vZt2O470R.jpg'}, {'credit_id': '52fe437e9251416c750127fd', 'department': 'Production', 'gender': 2, 'id': 1744, 'job': 'Producer', 'name': 'Robert Wise', 'profile_path': '/6EPkRgYsDMQOYmE9s1vZt2O470R.jpg'}, {'credit_id': '536514b9c3a36812180013d6', 'department': 'Art', 'gender': 2, 'id': 874, 'job': 'Production Design', 'name': 'Boris Leven', 'profile_path': None}, {'credit_id': '52fe437e9251416c75012809', 'department': 'Camera', 'gender': 2, 'id': 1762, 'job': 'Director of Photography', 'name': 'Richard H. Kline', 'profile_path': '/1b9iffgT1rS9ff2erVOaPhVowW8.jpg'}, {'credit_id': '536514dec3a368124a001462', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 3456, 'job': 'Costume Design', 'name': 'Helen Colvig', 'profile_path': None}, {'credit_id': '52fe437e9251416c750127f1', 'department': 'Writing', 'gender': 2, 'id': 4782, 'job': 'Novel', 'name': 'Michael Crichton', 'profile_path': '/lAQ6LYkhdVxa2tDSCOGxQZ3t0wO.jpg'}, {'credit_id': '536514c5c3a36812260013a1', 'department': 'Art', 'gender': 2, 'id': 5842, 'job': 'Art Direction', 'name': 'William H. Tuntke', 'profile_path': None}, {'credit_id': '52fe437e9251416c75012815', 'department': 'Editing', 'gender': 2, 'id': 10186, 'job': 'Editor', 'name': 'John W. Holmes', 'profile_path': None}, {'credit_id': '53651533c3a3681241001403', 'department': 'Visual Effects', 'gender': 2, 'id': 12112, 'job': 'Visual Effects', 'name': 'Douglas Trumbull', 'profile_path': '/gBnl4wS6WzKM0egvdtZyBT6L1xs.jpg'}, {'credit_id': '536514d2c3a368122000139b', 'department': 'Art', 'gender': 1, 'id': 12292, 'job': 'Set Decoration', 'name': 'Ruby R. Levitt', 'profile_path': None}, {'credit_id': '53651502c3a3681231001463', 'department': 'Costume & Make-Up', 'gender': 2, 'id': 14495, 'job': 'Hairstylist', 'name': 'Larry Germain', 'profile_path': None}, {'credit_id': '536514f4c3a3681238001363', 'department': 'Costume & Make-Up', 'gender': 0, 'id': 14498, 'job': 'Makeup Artist', 'name': 'Bud Westmore', 'profile_path': None}, {'credit_id': '52fe437e9251416c750127f7', 'department': 'Writing', 'gender': 2, 'id': 19459, 'job': 'Screenplay', 'name': 'Nelson Gidding', 'profile_path': None}, {'credit_id': '52fe437e9251416c7501280f', 'department': 'Editing', 'gender': 2, 'id': 30259, 'job': 'Editor', 'name': 'Stuart Gilmore', 'profile_path': None}, {'credit_id': '52fe437e9251416c75012803', 'department': 'Sound', 'gender': 2, 'id': 65513, 'job': 'Original Music Composer', 'name': 'Gil Mellé', 'profile_path': None}, {'credit_id': '53651548c3a368123100146e', 'department': 'Visual Effects', 'gender': 0, 'id': 1316340, 'job': 'Visual Effects', 'name': 'Jamie Shourt', 'profile_path': None}, {'credit_id': '5365155cc3a36812260013b0', 'department': 'Visual Effects', 'gender': 2, 'id': 1316341, 'job': 'Visual Effects', 'name': 'Albert Whitlock', 'profile_path': None}]
Name: crew, dtype: object
54235    []
Name: keywords, dtype: object
34564    [{'iso_639_1': 'ko', 'name': '한국어/조선말'}]
Name: spoken_languages, dtype: object
17507    [{'name': 'Italian International Film', 'id': 1429}, {'name': 'Selenia Cinematografica', 'id': 11398}]
Name: production_companies, dtype: object
52324    [{'id': 28, 'name': 'Action'}, {'id': 80, 'name': 'Crime'}]
Name: genres, dtype: object
11970    [{'iso_3166_1': 'US', 'name': 'United States of America'}]
Name: production_countries, dtype: object

In [53]:
# The 'cast', 'crew', and 'keywords' etc columns contain string representations of lists of dictionaries. 
# We need to convert these strings back into their original list/dictionary format for easier manipulation later on.
import ast
col_name=['cast','crew','keywords','spoken_languages','production_companies','genres','production_countries']
for item in col_name:
    df1[item] = df1[item].apply(lambda x: ast.literal_eval(x) if pd.notnull(x) else [])

In [54]:
#making a new column 'Actors_name' which contains the list of actor names for each movie
df1['Actors_name'] = df1['cast'].apply(lambda x: [i['name'] for i in x[:]])

In [55]:
df1['Actors_name'].sample(1)

43610    [George Hilton, Edwige Fenech, Manuel Zarzo, Salvatore Borghese, Chris Avram, Cris Huerta]
Name: Actors_name, dtype: object

In [56]:
df1['imdb_id'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 57402 entries, 0 to 57401
Series name: imdb_id
Non-Null Count  Dtype
--------------  -----
57385 non-null  object
dtypes: object(1)
memory usage: 448.6+ KB

In [57]:
df1['imdbId_fixed'] = df1['imdbId'].apply(
    lambda x: f"tt{int(x):07d}" if pd.notnull(x) else None
)
df1['imdbId_fixed'].sample(1)

20886    tt0911010
Name: imdbId_fixed, dtype: object

In [58]:
df1['imdb_id'] = df1['imdb_id'].fillna(df1['imdbId_fixed'])
df1['imdb_id'] = df1['imdb_id'].str.strip()

In [59]:
df1['imdb_id'].info()

<class 'pandas.core.series.Series'>
RangeIndex: 57402 entries, 0 to 57401
Series name: imdb_id
Non-Null Count  Dtype
--------------  -----
57402 non-null  object
dtypes: object(1)
memory usage: 448.6+ KB

In [60]:
# Check for missing values again after the transformations
(df1.isnull().mean() * 100).to_frame().T

,cast,crew,id,keywords,movieId,imdbId,tmdbId,adult,belongs_to_collection,budget,genres,homepage,imdb_id,original_language,original_title,overview,popularity,poster_path,production_companies,production_countries,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count,Actors_name,imdbId_fixed
0,0.0,0.0,2.215951,0.0,0.001742,0.001742,1.214243,0.0,86.826243,0.0,0.0,80.275949,0.0,0.019163,0.0,1.754294,1.484269,0.700324,0.0,0.0,0.153305,2.222919,2.682833,0.0,2.369255,51.236891,2.222919,2.222919,2.222919,2.222919,0.0,0.001742

In [61]:
df7=pd.read_csv('Datasets\imdb-dataset-of-50k-movie-reviews\IMDB Dataset.csv')

In [62]:
df7.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   review     50000 non-null  object
 1   sentiment  50000 non-null  object
dtypes: object(2)
memory usage: 781.4+ KB